[template.environment]
  STYTCH_PROJECT_ENV = "test"
  STYTCH_PROJECT_ID = "YOUR_STYTCH_PROJECT_ID"
  NEXT_PUBLIC_STYTCH_PUBLIC_TOKEN = "YOUR_STYTCH_PUBLIC_TOKEN"
  STYTCH_SECRET = "YOUR_STYTCH_SECRET"